"""Seed data for the default research profile."""

DEFAULT_RESEARCH_PROFILE: dict[str, object] = {
    "researcher_name": "Chad Alessi",
    "title": None,
    "institution": None,
    "primary_research_focus": "Human role in AI-augmented cybersecurity operations",
    "research_domains": [
        "human-AI teaming",
        "cybersecurity operations",
        "SOC alert triage",
        "OT cybersecurity",
        "immersive simulation",
        "VR/AR training",
        "trust calibration",
        "cognitive workload",
        "AI decision support",
        "cybersecurity workforce development",
        "critical infrastructure cybersecurity",
    ],
    "methods": [
        "controlled experiments",
        "within-subjects study design",
        "NASA-TLX",
        "xAPI telemetry",
        "decision accuracy measurement",
        "time-to-decision analysis",
        "qualitative post-task reflection",
    ],
    "target_funders": [
        "NSF",
        "NIST",
        "DHS",
        "DoD",
        "DOE",
        "foundations focused on AI, cybersecurity, education, and workforce development",
    ],
    "preferred_outputs": [],
    "keywords": [
        "human-centered AI",
        "trustworthy AI",
        "cyber workforce",
        "cyber range",
        "security operations center",
        "AI decision support",
        "cyber-physical systems security",
        "critical infrastructure resilience",
        "immersive learning",
        "cybersecurity education",
    ],
}
